version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data: 
    driver: local
    # driver_opts:
    #   path: ./data

networks:
  backend:
